token usage tracking (Issue #268)
browserbase/stagehand pull request #339
Opened 2024-12-27 01:39 UTC by andrewgcodes

# why
being able to track input/output/total tokens when using stagehand can be helpful for controlling costs, picking which model to use, etc.

See Issue #268 (https://github.com/browserbase/stagehand/issues/268)

# what changed
- Added LLMUsageEntry interface to track tokens per function call
- Implemented usage recording in OpenAI and Anthropic clients
- Added recordUsage() and getUsage() methods to Stagehand class
- Added getTotalTokensUsed() for aggregating total token usage

Works for act(), observe(), and extract()
12 files edited, added tests and and example (hackernews.ts) demonstrating how to log tokens used. Please see diff

# test plan
i wrote a few test cases and it seems to work but someone on the browserbase team should definitely test as well before merging!

2024-12-27 01:48 UTC, kamath commented
whoa!! thanks @andrewgcodes! i'll take a more detailed look at this in a bit, but thank you so much for taking the time to do this!

2024-12-27 02:14 UTC, kamath requested changes
Looking more, this is a phenomenal PR, and I sincerely appreciate you adding test cases.  

However, we're trying super hard to keep the Stagehand interface as minimal as possible to avoid adding unnecessary complexity to the end-user. Having a user write out the code I highlighted feels unnecessarily cumbersome. 

I acknowledge the frustration around token usage being a black box, and it's something we're actively fixing before the holiday break ends. We as the Browserbase team need to do better about this. 

I'm imagining an interface to act/extract/observe with something like the following:

```
const result = page.extract(extractOptions) # returns { ...extractResult, _stagehandTokenUsage: TokenUsageObject }
```

Let's talk more in #stagehand-discussion in the [Stagehand public Slack](https://join.slack.com/t/stagehand-dev/shared_invite/zt-2wknhxh47-VAed2iE8M8QSQTPpq2VK2Q) (I see you're part of this already but linking here for posterity)

2024-12-27 02:14 UTC, kamath commented on examples/hackernews.ts
> +    }
this isn't really elegant; ideally the user should be able to have all of this in one line

2024-12-27 07:07 UTC, andrewgcodes commented
Hey Anirudh, thanks for the quick review and kind words! I'll ping you on
the Slack

2024-12-27 07:20 UTC, sameelarif commented on lib/llm/LLMProvider.ts
> +    stagehand?: any,
Would definitely try to avoid using `any` here

2024-12-27 07:56 UTC, filip-michalsky commented
this is amazing! looking for the discussion in Slack. Also I see some Devin in here @andrewgcodes  :D

2025-02-13 02:00 UTC, cmaycumber commented
Is there any reason this stalled out? Can I help at all?

2025-05-08 22:23 UTC, seanmcguire12 commented
token usage can be accessed via `stagehand.metrics`

2025-05-08 22:23 UTC, closed without merging

2025-07-28 20:53 UTC, cyberpwnn commented
> token usage can be accessed via `stagehand.metrics`

No it cant, it doesnt work, its not documented, and it always shows 0. Please provide a way to access metrics.

2025-07-29 01:51 UTC, seanmcguire12 commented
@cyberpwnn either set `useAPI: false` or `env: "LOCAL"` in your stagehand constructor and you should see them if you run something like: 
```typescript
const metrics = stagehand.metrics;
console.log(JSON.stringify(metrics, null, 2));
```